# Artificial Neural Network

In [1]:
#importing libraries
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.1.0'

In [3]:
#importing dataset
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
#Dependent variables
y = dataset.iloc[:, -1].values
#independent variables

In [4]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [5]:
print(y)

[1 0 1 ... 1 1 0]


In [6]:
#Label Encoding the "Gender" column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [7]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [9]:
#One Hot Encoding the "Geography" column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [10]:
print(X[1:5])

[[0.0 0.0 1.0 608 0 41 1 83807.86 1 0 1 112542.58]
 [1.0 0.0 0.0 502 0 42 8 159660.8 3 1 0 113931.57]
 [1.0 0.0 0.0 699 0 39 1 0.0 2 0 0 93826.63]
 [0.0 0.0 1.0 850 0 43 2 125510.82 1 1 1 79084.1]]


In [11]:
#Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [12]:
#Scaling the feature vector
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [13]:
#initializing ANN
ann = tf.keras.models.Sequential()

In [14]:
#initialize hidden layers
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [16]:
#output layer the units should be equall to number of outputs
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [17]:
#compile to add optimizer, loss and metrics
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [18]:
#Training the ANN on the Training set
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Train on 8000 samples
Epoch 1/100
8000/8000 [==============================] - 3s 325us/sample - loss: 0.5955 - accuracy: 0.7245
Epoch 2/100
8000/8000 [==============================] - 1s 79us/sample - loss: 0.4571 - accuracy: 0.7977
Epoch 3/100
8000/8000 [==============================] - 1s 85us/sample - loss: 0.4339 - accuracy: 0.8059s - loss: 0
Epoch 4/100
8000/8000 [==============================] - 1s 85us/sample - loss: 0.4243 - accuracy: 0.8167
Epoch 5/100
8000/8000 [==============================] - 1s 76us/sample - loss: 0.4181 - accuracy: 0.8215
Epoch 6/100
8000/8000 [==============================] - 1s 77us/sample - loss: 0.4129 - accuracy: 0.8251
Epoch 7/100
8000/8000 [==============================] - 1s 82us/sample - loss: 0.4082 - accuracy: 0.8267
Epoch 8/100
8000/8000 [==============================] - 1s 80us/sample - loss: 0.4043 - accuracy: 0.8289
Epoch 9/100
8000/8000 [==============================] - 1s 81us/sample - loss: 0.4009 - accuracy: 0.8290s - loss: 0.3

8000/8000 [==============================] - 1s 76us/sample - loss: 0.3327 - accuracy: 0.8622
Epoch 78/100
8000/8000 [==============================] - 1s 75us/sample - loss: 0.3321 - accuracy: 0.8639
Epoch 79/100
8000/8000 [==============================] - 1s 81us/sample - loss: 0.3325 - accuracy: 0.8646
Epoch 80/100
8000/8000 [==============================] - 1s 79us/sample - loss: 0.3319 - accuracy: 0.8640
Epoch 81/100
8000/8000 [==============================] - 1s 76us/sample - loss: 0.3323 - accuracy: 0.8612
Epoch 82/100
8000/8000 [==============================] - 1s 80us/sample - loss: 0.3320 - accuracy: 0.8634
Epoch 83/100
8000/8000 [==============================] - 1s 74us/sample - loss: 0.3318 - accuracy: 0.8627
Epoch 84/100
8000/8000 [==============================] - 1s 76us/sample - loss: 0.3318 - accuracy: 0.8626
Epoch 85/100
8000/8000 [==============================] - 1s 78us/sample - loss: 0.3320 - accuracy: 0.8634
Epoch 86/100
8000/8000 [==========================

In [19]:
#single prediction
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


In [20]:
#predict on test dataset
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [21]:
#making confusion metrics(useful for classification)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1507   88]
 [ 194  211]]


0.859